// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/2beens/simple-go-service/internal/outbound (interfaces: idempotencyStore,repository,form3Creator,statusPublisher)
//
// Generated by this command:
//
//	mockgen -destination=service_mocks_test.go -package=outbound_test -typed=true . idempotencyStore,repository,form3Creator,statusPublisher
//

// Package outbound_test is a generated GoMock package.
package outbound_test

import (
	context "context"
	reflect "reflect"

	outbound "github.com/2beens/simple-go-service/internal/outbound"
	gomock "go.uber.org/mock/gomock"
)

// MockidempotencyStore is a mock of idempotencyStore interface.
type MockidempotencyStore struct {
	ctrl     *gomock.Controller
	recorder *MockidempotencyStoreMockRecorder
	isgomock struct{}
}

// MockidempotencyStoreMockRecorder is the mock recorder for MockidempotencyStore.
type MockidempotencyStoreMockRecorder struct {
	mock *MockidempotencyStore
}

// NewMockidempotencyStore creates a new mock instance.
func NewMockidempotencyStore(ctrl *gomock.Controller) *MockidempotencyStore {
	mock := &MockidempotencyStore{ctrl: ctrl}
	mock.recorder = &MockidempotencyStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockidempotencyStore) EXPECT() *MockidempotencyStoreMockRecorder {
	return m.recorder
}

// KeyExists mocks base method.
func (m *MockidempotencyStore) KeyExists(ctx context.Context, key string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "KeyExists", ctx, key)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// KeyExists indicates an expected call of KeyExists.
func (mr *MockidempotencyStoreMockRecorder) KeyExists(ctx, key any) *MockidempotencyStoreKeyExistsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "KeyExists", reflect.TypeOf((*MockidempotencyStore)(nil).KeyExists), ctx, key)
	return &MockidempotencyStoreKeyExistsCall{Call: call}
}

// MockidempotencyStoreKeyExistsCall wrap *gomock.Call
type MockidempotencyStoreKeyExistsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockidempotencyStoreKeyExistsCall) Return(arg0 bool, arg1 error) *MockidempotencyStoreKeyExistsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockidempotencyStoreKeyExistsCall) Do(f func(context.Context, string) (bool, error)) *MockidempotencyStoreKeyExistsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockidempotencyStoreKeyExistsCall) DoAndReturn(f func(context.Context, string) (bool, error)) *MockidempotencyStoreKeyExistsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetKey mocks base method.
func (m *MockidempotencyStore) SetKey(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetKey", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetKey indicates an expected call of SetKey.
func (mr *MockidempotencyStoreMockRecorder) SetKey(ctx, key any) *MockidempotencyStoreSetKeyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetKey", reflect.TypeOf((*MockidempotencyStore)(nil).SetKey), ctx, key)
	return &MockidempotencyStoreSetKeyCall{Call: call}
}

// MockidempotencyStoreSetKeyCall wrap *gomock.Call
type MockidempotencyStoreSetKeyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockidempotencyStoreSetKeyCall) Return(arg0 error) *MockidempotencyStoreSetKeyCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockidempotencyStoreSetKeyCall) Do(f func(context.Context, string) error) *MockidempotencyStoreSetKeyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockidempotencyStoreSetKeyCall) DoAndReturn(f func(context.Context, string) error) *MockidempotencyStoreSetKeyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Mockrepository is a mock of repository interface.
type Mockrepository struct {
	ctrl     *gomock.Controller
	recorder *MockrepositoryMockRecorder
	isgomock struct{}
}

// MockrepositoryMockRecorder is the mock recorder for Mockrepository.
type MockrepositoryMockRecorder struct {
	mock *Mockrepository
}

// NewMockrepository creates a new mock instance.
func NewMockrepository(ctrl *gomock.Controller) *Mockrepository {
	mock := &Mockrepository{ctrl: ctrl}
	mock.recorder = &MockrepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockrepository) EXPECT() *MockrepositoryMockRecorder {
	return m.recorder
}

// FindByID mocks base method.
func (m *Mockrepository) FindByID(ctx context.Context, id string) (outbound.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(outbound.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockrepositoryMockRecorder) FindByID(ctx, id any) *MockrepositoryFindByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*Mockrepository)(nil).FindByID), ctx, id)
	return &MockrepositoryFindByIDCall{Call: call}
}

// MockrepositoryFindByIDCall wrap *gomock.Call
type MockrepositoryFindByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockrepositoryFindByIDCall) Return(arg0 outbound.Payment, arg1 error) *MockrepositoryFindByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockrepositoryFindByIDCall) Do(f func(context.Context, string) (outbound.Payment, error)) *MockrepositoryFindByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockrepositoryFindByIDCall) DoAndReturn(f func(context.Context, string) (outbound.Payment, error)) *MockrepositoryFindByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// List mocks base method.
func (m *Mockrepository) List(ctx context.Context) ([]outbound.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]outbound.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockrepositoryMockRecorder) List(ctx any) *MockrepositoryListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*Mockrepository)(nil).List), ctx)
	return &MockrepositoryListCall{Call: call}
}

// MockrepositoryListCall wrap *gomock.Call
type MockrepositoryListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockrepositoryListCall) Return(arg0 []outbound.Payment, arg1 error) *MockrepositoryListCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockrepositoryListCall) Do(f func(context.Context) ([]outbound.Payment, error)) *MockrepositoryListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockrepositoryListCall) DoAndReturn(f func(context.Context) ([]outbound.Payment, error)) *MockrepositoryListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Save mocks base method.
func (m *Mockrepository) Save(ctx context.Context, p outbound.Payment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockrepositoryMockRecorder) Save(ctx, p any) *MockrepositorySaveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*Mockrepository)(nil).Save), ctx, p)
	return &MockrepositorySaveCall{Call: call}
}

// MockrepositorySaveCall wrap *gomock.Call
type MockrepositorySaveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockrepositorySaveCall) Return(arg0 error) *MockrepositorySaveCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockrepositorySaveCall) Do(f func(context.Context, outbound.Payment) error) *MockrepositorySaveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockrepositorySaveCall) DoAndReturn(f func(context.Context, outbound.Payment) error) *MockrepositorySaveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateStatus mocks base method.
func (m *Mockrepository) UpdateStatus(ctx context.Context, id string, status outbound.Status) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockrepositoryMockRecorder) UpdateStatus(ctx, id, status any) *MockrepositoryUpdateStatusCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*Mockrepository)(nil).UpdateStatus), ctx, id, status)
	return &MockrepositoryUpdateStatusCall{Call: call}
}

// MockrepositoryUpdateStatusCall wrap *gomock.Call
type MockrepositoryUpdateStatusCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockrepositoryUpdateStatusCall) Return(arg0 error) *MockrepositoryUpdateStatusCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockrepositoryUpdateStatusCall) Do(f func(context.Context, string, outbound.Status) error) *MockrepositoryUpdateStatusCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockrepositoryUpdateStatusCall) DoAndReturn(f func(context.Context, string, outbound.Status) error) *MockrepositoryUpdateStatusCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Mockform3Creator is a mock of form3Creator interface.
type Mockform3Creator struct {
	ctrl     *gomock.Controller
	recorder *Mockform3CreatorMockRecorder
	isgomock struct{}
}

// Mockform3CreatorMockRecorder is the mock recorder for Mockform3Creator.
type Mockform3CreatorMockRecorder struct {
	mock *Mockform3Creator
}

// NewMockform3Creator creates a new mock instance.
func NewMockform3Creator(ctrl *gomock.Controller) *Mockform3Creator {
	mock := &Mockform3Creator{ctrl: ctrl}
	mock.recorder = &Mockform3CreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockform3Creator) EXPECT() *Mockform3CreatorMockRecorder {
	return m.recorder
}

// CreatePayment mocks base method.
func (m *Mockform3Creator) CreatePayment(ctx context.Context, p outbound.Payment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePayment", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePayment indicates an expected call of CreatePayment.
func (mr *Mockform3CreatorMockRecorder) CreatePayment(ctx, p any) *Mockform3CreatorCreatePaymentCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePayment", reflect.TypeOf((*Mockform3Creator)(nil).CreatePayment), ctx, p)
	return &Mockform3CreatorCreatePaymentCall{Call: call}
}

// Mockform3CreatorCreatePaymentCall wrap *gomock.Call
type Mockform3CreatorCreatePaymentCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *Mockform3CreatorCreatePaymentCall) Return(arg0 error) *Mockform3CreatorCreatePaymentCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *Mockform3CreatorCreatePaymentCall) Do(f func(context.Context, outbound.Payment) error) *Mockform3CreatorCreatePaymentCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *Mockform3CreatorCreatePaymentCall) DoAndReturn(f func(context.Context, outbound.Payment) error) *Mockform3CreatorCreatePaymentCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockstatusPublisher is a mock of statusPublisher interface.
type MockstatusPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockstatusPublisherMockRecorder
	isgomock struct{}
}

// MockstatusPublisherMockRecorder is the mock recorder for MockstatusPublisher.
type MockstatusPublisherMockRecorder struct {
	mock *MockstatusPublisher
}

// NewMockstatusPublisher creates a new mock instance.
func NewMockstatusPublisher(ctrl *gomock.Controller) *MockstatusPublisher {
	mock := &MockstatusPublisher{ctrl: ctrl}
	mock.recorder = &MockstatusPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockstatusPublisher) EXPECT() *MockstatusPublisherMockRecorder {
	return m.recorder
}

// PublishPaymentStatus mocks base method.
func (m *MockstatusPublisher) PublishPaymentStatus(ctx context.Context, p outbound.Payment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishPaymentStatus", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishPaymentStatus indicates an expected call of PublishPaymentStatus.
func (mr *MockstatusPublisherMockRecorder) PublishPaymentStatus(ctx, p any) *MockstatusPublisherPublishPaymentStatusCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishPaymentStatus", reflect.TypeOf((*MockstatusPublisher)(nil).PublishPaymentStatus), ctx, p)
	return &MockstatusPublisherPublishPaymentStatusCall{Call: call}
}

// MockstatusPublisherPublishPaymentStatusCall wrap *gomock.Call
type MockstatusPublisherPublishPaymentStatusCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockstatusPublisherPublishPaymentStatusCall) Return(arg0 error) *MockstatusPublisherPublishPaymentStatusCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockstatusPublisherPublishPaymentStatusCall) Do(f func(context.Context, outbound.Payment) error) *MockstatusPublisherPublishPaymentStatusCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockstatusPublisherPublishPaymentStatusCall) DoAndReturn(f func(context.Context, outbound.Payment) error) *MockstatusPublisherPublishPaymentStatusCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
