// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/2beens/simple-go-service/internal/api (interfaces: paymentService)
//
// Generated by this command:
//
//	mockgen -destination=handler_mocks_test.go -package=api_test -typed=true . paymentService
//

// Package api_test is a generated GoMock package.
package api_test

import (
	context "context"
	reflect "reflect"

	outbound "github.com/2beens/simple-go-service/internal/outbound"
	gomock "go.uber.org/mock/gomock"
)

// MockpaymentService is a mock of paymentService interface.
type MockpaymentService struct {
	ctrl     *gomock.Controller
	recorder *MockpaymentServiceMockRecorder
	isgomock struct{}
}

// MockpaymentServiceMockRecorder is the mock recorder for MockpaymentService.
type MockpaymentServiceMockRecorder struct {
	mock *MockpaymentService
}

// NewMockpaymentService creates a new mock instance.
func NewMockpaymentService(ctrl *gomock.Controller) *MockpaymentService {
	mock := &MockpaymentService{ctrl: ctrl}
	mock.recorder = &MockpaymentServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpaymentService) EXPECT() *MockpaymentServiceMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockpaymentService) Get(ctx context.Context, id string) (outbound.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(outbound.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockpaymentServiceMockRecorder) Get(ctx, id any) *MockpaymentServiceGetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockpaymentService)(nil).Get), ctx, id)
	return &MockpaymentServiceGetCall{Call: call}
}

// MockpaymentServiceGetCall wrap *gomock.Call
type MockpaymentServiceGetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockpaymentServiceGetCall) Return(arg0 outbound.Payment, arg1 error) *MockpaymentServiceGetCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockpaymentServiceGetCall) Do(f func(context.Context, string) (outbound.Payment, error)) *MockpaymentServiceGetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockpaymentServiceGetCall) DoAndReturn(f func(context.Context, string) (outbound.Payment, error)) *MockpaymentServiceGetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// List mocks base method.
func (m *MockpaymentService) List(ctx context.Context) ([]outbound.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]outbound.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockpaymentServiceMockRecorder) List(ctx any) *MockpaymentServiceListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockpaymentService)(nil).List), ctx)
	return &MockpaymentServiceListCall{Call: call}
}

// MockpaymentServiceListCall wrap *gomock.Call
type MockpaymentServiceListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockpaymentServiceListCall) Return(arg0 []outbound.Payment, arg1 error) *MockpaymentServiceListCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockpaymentServiceListCall) Do(f func(context.Context) ([]outbound.Payment, error)) *MockpaymentServiceListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockpaymentServiceListCall) DoAndReturn(f func(context.Context) ([]outbound.Payment, error)) *MockpaymentServiceListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateStatusFromWebhook mocks base method.
func (m *MockpaymentService) UpdateStatusFromWebhook(ctx context.Context, paymentID string, status outbound.Status) (outbound.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatusFromWebhook", ctx, paymentID, status)
	ret0, _ := ret[0].(outbound.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateStatusFromWebhook indicates an expected call of UpdateStatusFromWebhook.
func (mr *MockpaymentServiceMockRecorder) UpdateStatusFromWebhook(ctx, paymentID, status any) *MockpaymentServiceUpdateStatusFromWebhookCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatusFromWebhook", reflect.TypeOf((*MockpaymentService)(nil).UpdateStatusFromWebhook), ctx, paymentID, status)
	return &MockpaymentServiceUpdateStatusFromWebhookCall{Call: call}
}

// MockpaymentServiceUpdateStatusFromWebhookCall wrap *gomock.Call
type MockpaymentServiceUpdateStatusFromWebhookCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockpaymentServiceUpdateStatusFromWebhookCall) Return(arg0 outbound.Payment, arg1 error) *MockpaymentServiceUpdateStatusFromWebhookCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockpaymentServiceUpdateStatusFromWebhookCall) Do(f func(context.Context, string, outbound.Status) (outbound.Payment, error)) *MockpaymentServiceUpdateStatusFromWebhookCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockpaymentServiceUpdateStatusFromWebhookCall) DoAndReturn(f func(context.Context, string, outbound.Status) (outbound.Payment, error)) *MockpaymentServiceUpdateStatusFromWebhookCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
