// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/2beens/simple-go-service/internal/payment (interfaces: httpDoer)
//
// Generated by this command:
//
//	mockgen -destination=client_mocks_test.go -package=payment_test -typed=true . httpDoer
//

// Package payment_test is a generated GoMock package.
package payment_test

import (
	http "net/http"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockhttpDoer is a mock of httpDoer interface.
type MockhttpDoer struct {
	ctrl     *gomock.Controller
	recorder *MockhttpDoerMockRecorder
	isgomock struct{}
}

// MockhttpDoerMockRecorder is the mock recorder for MockhttpDoer.
type MockhttpDoerMockRecorder struct {
	mock *MockhttpDoer
}

// NewMockhttpDoer creates a new mock instance.
func NewMockhttpDoer(ctrl *gomock.Controller) *MockhttpDoer {
	mock := &MockhttpDoer{ctrl: ctrl}
	mock.recorder = &MockhttpDoerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockhttpDoer) EXPECT() *MockhttpDoerMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockhttpDoer) Do(req *http.Request) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", req)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockhttpDoerMockRecorder) Do(req any) *MockhttpDoerDoCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockhttpDoer)(nil).Do), req)
	return &MockhttpDoerDoCall{Call: call}
}

// MockhttpDoerDoCall wrap *gomock.Call
type MockhttpDoerDoCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockhttpDoerDoCall) Return(arg0 *http.Response, arg1 error) *MockhttpDoerDoCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockhttpDoerDoCall) Do(f func(*http.Request) (*http.Response, error)) *MockhttpDoerDoCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockhttpDoerDoCall) DoAndReturn(f func(*http.Request) (*http.Response, error)) *MockhttpDoerDoCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
